package java_basictoadvance;

public class WhyNotToPushClassFiles {
	public static void main(String[] args) {
		System.out.println("✅ What's the difference?");
		System.out.println("File_Type\tPurpose");
		System.out.println(".java\t\tYour source code written in Java");
		System.out.println(".class\t\tThe compiled bytecode generated by the Java compiler (javac) — this is what the JVM actually runs");

		System.out.println("\n🛠️ Why .class Files Are There:");
		System.out.println("If you're using an IDE like Eclipse, it automatically compiles your .java files into .class files and places them in the bin/ or out/ directory.");
		System.out.println("If you're not careful, these .class files can end up in your version-controlled folder.");

		System.out.println("\n❌ You Should NOT Push .class Files to Git");
		System.out.println(".class files are build artifacts, not source code. Including them in your repo:");
		System.out.println("- Clutters the repository");
		System.out.println("- Causes unnecessary merge conflicts");
		System.out.println("- Increases repo size\n");

		//\033[1m = start bold
		//\033[0m = reset to normal
		// ANSI code for bold is \033[1m and reset is \033[0m
		System.out.println("\033[1mSummary: (This is bold text in supported terminals)\033[0m"
				+ "\n✅ What's the difference? File Type: .java - Your source code written in Java,"
				+ " \n.class - The compiled bytecode generated by the Java compiler (javac) — this is what the JVM actually runs."
				+ " \n🛠️ Why .class Files Are There: If you're using an IDE like Eclipse,"
				+ " \nit automatically compiles your .java files into .class files and places them in the bin/ or out/ directory."
				+ " \nIf you're not careful, these .class files can end up in your version-controlled folder."
				+ " \n❌ You Should NOT Push .class Files to Git: .class files are build artifacts, not source code. "
				+ "\nIncluding them in your repo: Clutters the repository, Causes unnecessary merge conflicts, Increases repo size.");
		System.out.println("checking .class");
		System.out.println("checking .class");
	}
}
